# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_extrainfouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfouser',
            name='followers',
            field=models.ManyToManyField(related_name='followed_by', to='home.ExtraInfoUser'),
        ),
    ]
