# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20180124_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfouser',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='extrainfouser',
            name='user',
        ),
        migrations.AddField(
            model_name='extrainfouser',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extrainfouser',
            name='follows',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
