# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180124_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmodel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='photofeed', to=settings.AUTH_USER_MODEL),
        ),
    ]
